Revert "jsonutil: use goccy/go-json for JSON encoding and decoding"
This reverts commit c152b3cef209cae56f705c6ab359b614196f86be.

Potentially related to a memory corruption crash, revert
goccy/go-json for now.

	runtime: nameOff 0x1013fc0 out of range 0xf3d020 - 0x13a3ca1
	fatal error: runtime: name offset out of range

	goroutine 7 [running]:
	runtime.throw({0x112d61d, 0x100d720})
		go/src/runtime/panic.go:1198 +0x71 fp=0xc02bb7f590 sp=0xc02bb7f560 pc=0x450091
	runtime.resolveNameOff(0xc02bb7f618, 0x1013fc0)
		go/src/runtime/type.go:195 +0x265 fp=0xc02bb7f5e8 sp=0xc02bb7f590 pc=0x479045
	reflect.resolveNameOff(0x1, 0x133c1a8)
		go/src/runtime/runtime1.go:496 +0x19 fp=0xc02bb7f608 sp=0xc02bb7f5e8 pc=0x47fb59
	reflect.(*rtype).nameOff(...)
		go/src/reflect/type.go:725
	reflect.(*rtype).String(0x133c1a8)
		go/src/reflect/type.go:795 +0x25 fp=0xc02bb7f628 sp=0xc02bb7f608 pc=0x4db5e5
	fmt.(*pp).handleMethods(0xc00199c0d0, 0x2bb7f908)
		go/src/fmt/print.go:626 +0x383 fp=0xc02bb7f8d8 sp=0xc02bb7f628 pc=0x518c83
	fmt.(*pp).printArg(0xc00199c0d0, {0x10d1380, 0x133c1a8}, 0x73)
		go/src/fmt/print.go:709 +0x693 fp=0xc02bb7f978 sp=0xc02bb7f8d8 pc=0x519833
	fmt.(*pp).doPrintf(0xc00199c0d0, {0x111c854, 0x1a}, {0xc02bb7faf0, 0x84538a, 0xc01b54c125})
		go/src/fmt/print.go:1026 +0x288 fp=0xc02bb7fa70 sp=0xc02bb7f978 pc=0x51c0e8
	fmt.Sprintf({0x111c854, 0x1a}, {0xc02bb7faf0, 0x1, 0x1})
		go/src/fmt/print.go:219 +0x59 fp=0xc02bb7fac8 sp=0xc02bb7fa70 pc=0x5163f9
	github.com/goccy/go-json/internal/errors.(*UnsupportedTypeError).Error(0xc0035c8000)
		goget/pkg/mod/github.com/goccy/go-json@v0.7.7/internal/errors/error.go:100 +0x52 fp=0xc02bb7fb10 sp=0xc02bb7fac8 pc=0x5bd6d2